"""Add connection to OAuth

Revision ID: 549c1b8c122d
Revises: d3f0162069bc
Create Date: 2024-12-09 17:09:53.578665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549c1b8c122d'
down_revision: Union[str, None] = 'd3f0162069bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_provider',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='users'
    )
    op.create_unique_constraint(None, 'login_record', ['id'], schema='users')
    op.create_unique_constraint(None, 'role', ['id'], schema='users')
    op.add_column('user', sa.Column('email', sa.String(length=225), nullable=True), schema='users')
    op.create_unique_constraint(None, 'user', ['id'], schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='users', type_='unique')
    op.drop_column('user', 'email', schema='users')
    op.drop_constraint(None, 'role', schema='users', type_='unique')
    op.drop_constraint(None, 'login_record', schema='users', type_='unique')
    op.drop_table('auth_provider', schema='users')
    # ### end Alembic commands ###
